# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_scrape_game_data.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/01_scrape_game_data.ipynb 2
from nbdev.showdoc import *
import pandas as pd, pathlib
#import gluonts
from nbdev import *
import urllib.request
from bs4 import BeautifulSoup
from fastcore.test import *
import requests


# %% ../nbs/01_scrape_game_data.ipynb 11
def foo(): pass
