# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_set.ipynb.

# %% auto 0
__all__ = ['vball_set', 'foo']

# %% ../nbs/02_set.ipynb 2
from nbdev.showdoc import *
from nbdev import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# %% ../nbs/02_set.ipynb 7
class vball_set:
    '''
    Creates a set with and times the length of a set
    '''
    def __init__(self, 
             div:str): # The division of the set [PM, PW, RM, RW]
        # Set the point variables
        divisions = ["PM", "PW", "RM", "RW"]
        assert div in str(divisions), "Division is not valid must be: PM, PW, RM or RW"
        if div == "PM" or div == "RM":
            self.point_mean = 4.99
            self.point_var = 4.35**2
            self.rest_mean = 29.02
            self.rest_var = 19.44**2
        else: 
            self.point_mean = 6.88
            self.point_var = 5.92**2
            self.rest_mean = 28.92
            self.rest_var = 18.21**2
            
        # Determine the number of points. 
        self.points = 25 + int(np.random.binomial(23, 0.85, 1))
        

# %% ../nbs/02_set.ipynb 9
def foo(): pass
